//------------------------------------------------------------------------------
//
//  float.h - ANSI C header file for floating-point calculations
//
//  Edit History:
//  -------------
//  17Aug94 (fpj) - Original creation.
//
//------------------------------------------------------------------------------

// ++++
// This software is in the public domain.  It may be freely copied and used
// for whatever purpose you see fit, including commerical uses.  Anyone
// modifying this software may claim ownership of the modifications, but not
// the complete derived code.  It would be appreciated if the authors were
// told what this software is being used for, but this is not a requirement.

//   THIS SOFTWARE IS PROVIDED BY THE AUTHORS "AS IS" AND ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
//   OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
//   TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
//   USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//----

#ifndef _FLOAT_H_
#define _FLOAT_H_

#ifndef _BASELINE_H_

#include <baseline.h>

#endif // _BASELINE_H_


// #define FLT_RADIX
// #define FLT_MANT_DIG
// #define DBL_MANT_DIG
// #define LDBL_MANT_DIG
// #define FLT_DIG
// #define DBL_DIG
// #define LDBL_DIG
// #define FLT_MIN_EXP
// #define DBL_MIN_EXP
// #define LDBL_MIN_EXP
// #define FLT_MIN_10_EXP
// #define DBL_MIN_10_EXP
// #define LDBL_MIN_10_EXP
// #define FLT_MAX_EXP
// #define DBL_MAX_EXP
// #define LDBL_MAX_EXP
// #define FLT_MAX_10_EXP
// #define DBL_MAX_10_EXP
// #define LDBL_MAX_10_EXP
// #define FLT_MAX
// #define DBL_MAX
// #define LDBL_MAX
// #define FLT_EPSILON
// #define DBL_EPSILON
// #define LDBL_EPSILON
// #define FLT_MIN
// #define DBL_MIN
// #define LDBL_MIN

#endif  // _FLOAT_H_

