CLIB01/CREATE/LIST=CLIB01
_main
dirscan procarg progarg dosdrvf
femsg femsg2 errmsg
getenv
abs div atoi axtoi log longdiv rotate
add2sdt sdt2str ddt2str sdtsub
exit atexit
setjmp system
perror qsort
printf ferror fflush fgets fopen puts fputs fread getchar fgetc fseek
ftell remove rename tmpnam ungetc fwrite putchar fputc fclose feof fgetstr
fexist fgtfinfo fisctrm getch getche getfarg getfinfo isctrm
_fsetup _fmode
getspace
global
gtrqname
setvectr
strtol strtoul stricmp strlower strmov strnchr strnicmp strnmov strupr  xstrncmp strcat
strchr strcmp strcpy strcspn strerror strlen strncat strncmp strncpy strpbrk
strrchr strspn strstr strtok
isalnum isalpha iscntrl isdigit isgraph islower isprint ispunct isspace isupper
isxdigit tolower toupper
malloc heapsort sbrk
memchr memcmp memcpy memmove memset
_iob
$nextblk $dumpblk
kerdef svcdef
_assert _chrtbl _errno
nullfunc
