LIBC01/CREATE/LIST=LIBC01
_main
dirscan procarg progarg dosdrvf
femsg femsg2 errmsg
getenv
abs div atoi axtoi log longdiv rotate
add2sdt sdt2str ddt2str sdtadd sdtsub
exit atexit
setjmp system
perror qsort
printf ferror fflush 
fopen puts fputs fread getchar fseek
ftell remove rename tmpnam ungetc fwrite putchar
fclose feof fgets fgetsl fgetstr fgetc fputc
fexist fgtfinfo fisctrm getch getche getfarg getfinfo isctrm
_fsetup _fmode
getspace
gtrqname
setvectr
strtol strtoul stricmp strlower strmov strnchr strnicmp strnmov strupr strnupr
xstrncmp strcat
strchr strcmp strcpy strcspn strerror strlen strncat strncmp strncpy strpbrk
strrchr strspn strstr strtok
isalnum isalpha iscntrl isdigit isgraph islower isprint ispunct isspace
isupper isxdigit tolower toupper
malloc heapsort sbrk
memchr memcmp memcpy memmove memset
_iob
$nextblk $dumpblk
kerdef svcdef
_assert _chrtbl _errno
nullfunc

