//------------------------------------------------------------------------------
//
//  keys.h
//
//  Copyright (c) 1984-1994 Saguaro Software, Ltd.  All rights reserved.
//  Copyright (c) 1994-1995 Allegro Systems, Ltd.  All rights reserved.
// 
//
//  Written by Bruce R. Nevins
// 
//  Edit History:
//  -------------
//  06/16/91(brn) - Created first version
//  03/22/92(brn) - Added more key definitions
// 
//------------------------------------------------------------------------------

#ifndef __KEYS_H__

#define UPARROW		(23)
#define DOWNARROW	(25)
#define PGUP		(19)
#define PGDN		(22)

#define KEYPUPARROW	(37)
#define KEYPDOWNARROW	(45)
#define KEYPPGUP	(38)
#define KEYPPGDN	(46)

#define F1		(1)
#define F2		(2)
#define F3		(3)
#define F4		(4)
#define F5		(5)
#define F6		(6)
#define F7		(7)
#define F8		(8)
#define F9		(9)
#define F10		(0)
#define F11		(11)
#define F12		(12)

#endif
