//------------------------------------------------------------------------------
//
//  shelljmp.h - Reference data for long jumps
//
//  Copyright (c) 1992-1994 Saguaro Software, Ltd.  All rights reserved.
//  Copyright (c) 1994-1995 Allegro Systems, Ltd.  All rights reserved.
//
//
//  Written by Bruce R. Nevins
//
//  Edit History:
//  -------------
//  08/18/92(brn) - Created first version
//  04/01/94(brn) - Added jump for batch mode
//
//------------------------------------------------------------------------------

#ifndef __SHELLJMP_H__
extern jmp_buf  rstbuf;
extern jmp_buf  batrstbuf;
#endif

