BATOPT ERRP=ON

ADDUNIT NET UNIT=4 TYPE=ERTA SLOT=17

ADDUNIT SNAP: UNIT=4 NETDEV=NET4
DEVCHAR SNAP4: SAP=0FF-FF
rem DEVCHAR/Q SNAP4: SAP=0AA-AA
ADDUNIT ARP: UNIT=4 SNAPDEV=SNAP4
DEVCHAR/Q ARP4: ETYPE=8-6

ADDUNIT IPS: UNIT=4 SNAPDEV=SNAP4
DEVCHAR/Q IPS4: CHKSUMH=FULL

DEVCHAR/Q IPS4: ETYPE=8-0 ARPDEV=ARP4
DEVCHAR/Q IPS4: IPADDR=10.1.1.21 SUBMASK=0FF-0-0-0
DEVCHAR/Q IPS4: DOMAIN=JRG2.ALLEGROSYS.COM 
DEVCHAR/Q IPS4: DRT1ADDR=10.0.0.1

ADDUNIT TCP: UNIT=4 IPSDEV=IPS4

DEVCHAR/q TCP4 IPPROT=6
ADDUNIT UDP UNIT=4 IPSDEV=IPS4
DEVCHAR/q UDP4 IPPROT=17
ADDUNIT RCP UNIT=4 UDPDEV=UDP4
DEVCHAR/Q RCP4 ACCESS=LANA

ADDUNIT XFP UNIT=4 RCPDEV=RCP4

DEVCHAR/Q RCP4 CON60=XFPSRV^1^1
