extern int    version;
extern int    editnum;
extern uchar  ptype;
extern char   itype;
extern long   offset;
extern long   rdoffset;
extern long   symtblsize;
extern long   stbtotal;
extern int    seggbn;
extern int    mscgbn;
extern int    pscgbn;
extern int    symsize;
extern int    mltcnt;
extern int    undefcnt;
extern long   outdd;
extern long   stradr;
extern struct pd *strpsd;
extern long   stkadr;
extern struct pd *stkpsd;
extern long   dbgadr;
extern struct pd *dbgpsd;
extern struct pstk *polspnt;
extern struct pstk  polstk[];
extern struct pd  abspsd;
extern struct pd *curpsd;
extern struct md *curmsd;
extern struct sd *cursgd;
extern struct pd *stbpsd;
extern struct md *stbmsd;
extern struct msgb *msgbhead;
extern struct msgb *msgbtail;
extern struct pd **psnumpnt;
extern int    psnumcnt;
extern struct md **msnumpnt;
extern int    msnumcnt;
extern struct sd **segnumpnt;
extern int    segnumcnt;
extern uchar *msbuffer;
extern int    mscount;
extern ulong  msoffset;
extern void (*msdispatch)(void);
extern ulong  stbsize;
extern ulong  stboffset;
extern ulong  stbnum;
extern ulong  stbxsp;
extern int    seccnt;
extern int    sectype;
extern int    sectypx;
extern long   objdd;
extern long   symdd;
extern int    objcnt;
extern uchar *objpnt;
extern int    objamnt;
extern long   objblk;
extern struct objblk *firstobj;
extern struct objblk *curobj;
extern struct objblk *prevobj;
extern struct modblk *curmod;
extern char  *firstname;
extern char  *firstext;
extern char  *symbufr;
extern char  *symbpnt;
extern int    symbcnt;
extern long   symlength;
extern long   symtotal;
extern struct sd  *sgdhead;
extern struct sd  *sgdtail;
extern struct sy **symnumbase;
extern struct sy  *hashtbl[];
extern struct sy  *importhead;
extern struct sy  *importtail;
extern long   importnum;
extern long   importnumoffset;
extern long   importos;
extern struct sy *exporthead;
extern struct sy *exporttail;
extern long   exportnum;
extern long   exporttotal;
extern struct _mab segnummem;
extern struct _mab msectnummem;
extern struct _mab psectnummem;
extern struct _mab symnummem;
extern struct _mab lnamesmem;
extern uchar *auxloc;
extern uchar *objloc;
extern uchar *objbuf;
extern char  *outfsp;
extern char  *mapfsp;
extern char  *symfsp;
extern FILE  *mapfp;
extern long   debgaddr;
extern int    opsymsz;
extern char   opsymwrd;
extern char   opsymord;
extern char   prgname[];
extern char   inpext[];
extern char   outext[];
extern char   symext[];
extern char   mapext[];
extern char   cmdext[];
extern char   objtype;
extern char   modtype;
extern char   needrun;
extern char   needmap;
extern char   needsym;
extern char   lowfirst;
extern char   libflag;
extern char   mapflag;
extern char   sumflag;
extern char   debugflag;
extern char   done;
extern char   errorflg;
extern char   symblk;
extern char   modname[];
extern char   symbuf[];
extern char   haveweak;
extern char   havelazy;
