@ECHO OFF
BATOPT ERRP=ON
SYSCHAR/Q V86BASE=0 INITIAL=YES
CLSCHAR/Q DISK: NUMDBUF=2000 NUMSBUF=1000
LOGICAL/Q/SYS O:=SYS:\OVR\
LKELOAD FDKADRV BOOT
DOSDRIVE/Q

DEVCHAR/Q D0: WTMAX=16
DEVCHAR/Q D0P1: WTMAX=16

LKELOAD S3ADRV

LKELOAD MOUSEACLS
ADDUNIT MOUSEA: UNIT=0 IOREG=0x2F8 INT=3
DEVCHAR/Q MOUSEA0: CONDEV=0

LOGICAL/Q/SYS AUX:=_TRM1:
LOGICAL/Q/SYS COM1:=_TRM1:
LOGICAL/Q/SYS COM2:=_TRM2:
rem LOGICAL/Q/SYS LZPRT:=_SPL1:
LOGICAL/Q/SYS LZPRT:=_TRM1:

LOGICAL/Q/SYS PRN:=_SPL1:
LOGICAL/Q/SYS OVR:=SYS:\OVR\
LOGICAL/Q/SYS NET:=XFP0:
LOGICAL/Q/SYS NDG:=UDP0:
LOGICAL/Q/SYS S:=SYS:

CRSHSAVE

rem LKELOAD PPRCLS
rem DOSLPT

rem LKELOAD SERADRV
rem ADDUNIT TRM: UNIT=1 TYPE=SERA IOREG=0x3F8 INT=4

rem DEVCHAR/Q TRM1: IRATE=9600 IINFLOW=DTR IOUTFLOW=DSR SESSION=NO
rem ADDUNIT TRM: UNIT=2 TYPE=SERA IOREG=0x2F8 INT=3
rem DEVCHAR/Q TRM2: IRATE=60000 IINFLOW=DTR IOUTFLOW=DSR SESSION=NO
rem ADDUNIT TRM: UNIT=4 TYPE=SERA IOREG=0x2E8 INT=2
rem DEVCHAR/Q TRM4: IRATE=60000 IINFLOW=DTR IOUTFLOW=DSR SESSION=NO

SYMBIONT SCREEN 0:16

DEVCHAR/Q TRM0S1: IOUTFLOW=XON OUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S2: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S3: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S4: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S5: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S6: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S7: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S8: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S9: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S10: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S11: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S12: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S13: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S14: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S15: IOUTFLOW=XON SESSION=YES VERTFREQ=80
DEVCHAR/Q TRM0S16: IOUTFLOW=XON SESSION=YES VERTFREQ=80

rem LKELOAD SPLCLS
rem ADDUNIT SPL: UNIT=1
rem DEVCHAR/Q SPL1: SPLSPEC=E:\SPOOL\S01_#4.TMP CLSNAME=S01_#4.SPL CLSTIME=5
rem SYMBIONT UNSPOOL UNIT=1 OUTPUT=_TRM1: DIRECT=C:\SPOOL\

LKELOAD SCSICLS
LKELOAD SCSIADTA
LKELOAD SDSKDRV
ADDUNIT SCSI UNIT=0 TYPE=ADTA IOREG=0x330

ADDUNIT DISK UNIT=2 TYPE=SDSK SCSIDEV=SCSI0 SCSITAR=4
DEVCHAR D2 DOSNAME1=K DOSNAME2=L

rem ADDUNIT DISK UNIT=3 TYPE=SDSK SCSIDEV=SCSI0 SCSITAR=6
rem DEVCHAR D3 DOSNAME1=M DOSNAME2=N

LKELOAD CDRACLS
ADDUNIT DISK UNIT=4 TYPE=SDSK SCSIDEV=SCSI0 SCSITAR=2
DEVCHAR D4: DOSNAME=Y
SETENV/Q/SYS COMSPEC = C:\XOS\CMD\COMMAND.COM
CALL XOSCFG:\USTARTUP.BAT
