//-------------------------------------------------------------------------
//++++
// This software is in the public domain.  It may be freely copied and used
// for whatever purpose you see fit, including commerical uses.  Anyone
// modifying this software may claim ownership of the modifications, but not
// the complete derived code.  It would be appreciated if the authors were
// told what this software is being used for, but this is not a requirement.

//   THIS SOFTWARE IS PROVIDED BY THE AUTHORS "AS IS" AND ANY EXPRESS OR
//   IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//   OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//   IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT,
//   INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
//   BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
//   OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
//   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
//   TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
//   USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//----

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <xos.h>
#include <xossvc.h>
#include <xoserr.h>
#include <xosrtn.h>
#include <progarg.h>
#include <proghelp.h>
#include <xoserrmsg.h>
#include <errno.h>

#define VERSION 1
#define EDITNO 0

#define AF(func) (int (*)(arg_data *))func

// The program information block
Prog_Info pib;

FILE  *file1;
FILE  *file2;

char   copymsg[] = "";
char   example[] = "{/options} file1 file2";
char   description[] = "UNDUMP converts a file generated by DUMP into a "
    "binary file.";
char   prgname[] = "UNDUMP";
char   envname[] = "^XOS^UNDUMP^OPT";


char *fnm1 = NULL;
char *fnm2 = NULL;

long  quiet = FALSE;
long  mute = FALSE;

int cmdlinefile(char *);
int gethex(char *str);
int hexval(int val);

arg_spec options[] =
{
    {"H*ELP"  , 0, NULL, AF(opthelp), 0, "This message."},
    {"?"      , 0, NULL, AF(opthelp), 0, "This message."},
    {"Q*UIET" , ASF_BOOL|ASF_STORE, NULL, &quiet, TRUE, "No output, except error messages."},
    {"M*UTE"  , ASF_BOOL|ASF_STORE, NULL, &mute, TRUE, "No output, even error messages."},
    {NULL     , 0, NULL, AF(NULL)    , 0}
};


void main(
    int   argc,
    char *argv[])

{
	int   value;
	char  bufr[512];
	char *pnt;
    char *foo[2];

    reg_pib(&pib);
    init_Vars();
    if(svcSysFindEnv(0, envname, NULL, bufr, sizeof(bufr), NULL) > 0)
    {
		foo[0] = bufr;
		foo[1] = '\0';
		progarg(foo, 0, options, NULL, cmdlinefile,
				(void (*)(char *, char *))NULL, (int (*)(void))NULL, NULL);
    }
    if (argc>1)
    	++argv;
	progarg(argv, 0, options, NULL, cmdlinefile,
			(void (*)(char *, char *))NULL, (int (*)(void))NULL, NULL);
	if (mute)
		quiet=TRUE;
	if (fnm1 == NULL || fnm2 == NULL)
	{
		if ( !mute )
			fputs("? UNDUMP: Two file names are required\n", stderr);
		exit (EXIT_INVSWT);
    }
    if (argc < 3 || argc > 6)
    {
		if (!mute)
			fputs("? UNDUMP: Invalid number of options provided\n", stderr);
		exit (EXIT_INVSWT);
    }

	if ((file1 = fopen(fnm1, "rb")) == NULL)
		femsg2(prgname, "Cannot open input file", -errno, NULL);
	if ((file2 = fopen(fnm2, "wb")) == NULL)
		femsg2(prgname, "Cannot open input file", -errno, NULL);
    while (fgets(bufr, sizeof(bufr), file1) != NULL)
    {
		if ((pnt = strchr(bufr, '>')) != NULL)
		{
			pnt++;
			while (pnt[0] == ' ' && isxdigit(pnt[1]) && isxdigit(pnt[2]))
			{
				value = hexval(pnt[1]) * 16 + hexval(pnt[2]);
				if (fwrite(&value, 1, 1, file2) < 0)
					femsg2(prgname, "Error writing output file", -errno, NULL);
				pnt += 3;
			}
		}
    }
	if (fclose(file2) < 0)
		femsg2(prgname, "Error closing output file", -errno, NULL);
	fclose(file1);
	exit (0);
}

//***************************************************
// Function: cmdlinefile - Open the requested file
// Returned: TRUE
//***************************************************

int cmdlinefile(
    char *f)

{
    if (fnm1 == NULL)
    {
		fnm1 = malloc(strlen(f) + 1);
		strcpy(fnm1, f);
    }
    else
    {
		if (fnm2 == NULL)
		{
			fnm2 = malloc(strlen(f) + 1);
			strcpy(fnm2, f);
		}
		else
		{
			if (!mute)
			fputs("? UNDUMP: Too many file names provided\n", stderr);
			exit (EXIT_INVSWT);
		}
    }
    return (TRUE);
}

//***********************************************************
// Function: init_Vars - Set up the program information block
// Returned: Nothing
//***********************************************************

void init_Vars(void)

{
    // Set defaults of control variables

    quiet = FALSE;
    mute = FALSE;

    // Set Program Information Block variables

    pib.opttbl = options; 		// Load the option table
    pib.build = __DATE__;
    pib.majedt = VERSION;		// major edit number
    pib.minedt = EDITNO;		// minor edit number
    pib.copymsg = copymsg;
    pib.prgname = prgname;
    pib.desc = description;
    pib.example = example;
    pib.errno = 0;
    getTrmParms();
    getHelpClr();
}

int hexval(
	int val)

{
	printf("=%c", val);

	if (val > '9')
		val += 9;

	printf("-%01.1X", val & 0x0F);

	return (val & 0x0F);
}
