SYMBIONT PCCARD
SERVER PCCARD REG PCCARD=PCCB0
SERVER PCCARD DEV PCCARD=PCCB0:0 CLASS=DISK TYPE=HDKA DOSNAMES=F INDEX=1 UNIT=2 IOREG=0x180 INT=11
SERVER PCCARD DEV PCCARD=PCCB0:1 CLASS=DISK TYPE=HDKA DOSNAMES=G INDEX=1 UNIT=3 IOREG=0x150 INT=9

